import avatarImg from "../../public/small-logo.svg";
import nameAvatarImg from "../../public/SSTTEK_DARK_Logo.svg";

export const UserListData = [
  {
    avatar: avatarImg,
    nameAvatar: nameAvatarImg,
    userName: "",
    lastMessage: "Living the dream",
    userStatus: "online",
    userTime: "",
    color: "",
    isActive: true,
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Brandon Andrews",
    lastMessage: "Hello there!",
    userStatus: "offline",
    userTime: "3 hours ago",
    color: "#79E49F",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Clyton Day",
    lastMessage: "Yes, of course. Thanks",
    userStatus: "offline",
    userTime: "Yesterday",
    color: "#FF728D",
    unread: true,
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Bernice Clark",
    lastMessage: "This is a question regional.",
    userStatus: "online",
    userTime: "",
    color: "#FEB467",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Christine Fields",
    lastMessage: "Do you need help with this work?",
    userStatus: "online",
    userTime: "",
    color: "#D498D4",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Mike Morgan",
    lastMessage: "Choose the perfect answer.",
    userStatus: "offline",
    userTime: "Jul 27",
    color: "#FF927A",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Callie Schmidt",
    lastMessage: "Yes thanks!",
    userStatus: "offline",
    userTime: "Jul 23",
    color: "#79D1E4",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Herbert Watkins",
    lastMessage: "Of course, send as an...",
    userStatus: "offline",
    userTime: "Jul 23",
    color: "#A9B8EA",
  },
  {
    avatar: "",
    nameAvatar: "",
    userName: "Test Test",
    lastMessage: "test",
    userStatus: "offline",
    userTime: "Jul 20",
    color: "#D498D4",
  },
];
